# This workflow will be used to verify a pull request, this is to make sure that on pull requests it doesn't mess with the already available binary on the main workflow
name: Pull Request Test

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - '**.json'
      - '**.yml'
      - 'LICENSE'
      - '!.github/workflows/pull-request.yml'
      - '.gitignore'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            file-name: ue-asset-dumper
            prefix: linux

          - os: macOS-latest
            file-name: ue-asset-dumper
            prefix: macos

          - os: windows-latest
            file-name: ue-asset-dumper.exe
            prefix: windows

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get libdbus if Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libdbus-1-dev

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.prefix }}-${{ matrix.file-name }}
          path: ./target/release/${{ matrix.file-name }}
          if-no-files-found: error
